language: python

matrix:
  include:
    - python: 3.3
      env:
        - COVERAGE=false
    - python: 3.4
      env:
        - COVERAGE=false
    - python: 3.5
      env:
        - COVERAGE=true

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda


install:
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION scipy nose seaborn
  - source activate test
  - conda install --yes coverage docopt requests pyyaml
  - pip install coveralls
  - pip install .

script:
  - python check_paramnormal.py --with-coverage --cover-package=paramnormal --verbose

after_success:
  - if [ ${COVERAGE} = true ]; then coveralls; fi

