package:
  name: paramnormal
  version: v0.2.dev

source:
  path: ../..

build:
  number: 1
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - nose

test:
  imports:
    - paramnormal

  commands:
    - python -c "import paramnormal; paramnormal.test()"

  requires:
    - nose

about:
  home: http://phobson.github.io/paramnormal/
  license:  BSD License
  summary: 'Conventionally parameterized probability distributions.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml/configure
